### ISSUE TITLE
Signal information missing from FAST5 files

### ISSUE THREAD

**Issue by nodrogluap** [hyeshik/sars-cov-2-transcriptome#1]
Hi,

First of all, thanks for posting all your data, I analyze RNA in raw signal space so this is very helpful! I have a problem though, the FAST5 files seem to be (stripped of / are missing / have misformatted) the raw signal.  Maybe osf.io has corrupted this somehow? For example: h5dump FAN04901_90bfe2e3_1.fast5

...
   GROUP "read_0009417a-7107-4c13-9059-4a0c5744043c" {
      ATTRIBUTE "pore_type" {
         DATATYPE  H5T_STRING {
            STRSIZE 7;
            STRPAD H5T_STR_NULLPAD;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
         DATA {
         (0): "not_set"
         }
      }
...
      GROUP "Raw" {
         ATTRIBUTE "duration" {
            DATATYPE  H5T_STD_U32LE
            DATASPACE  SCALAR
            DATA {
            (0): 436555
            }
         }
...
         ATTRIBUTE "read_number" {
            DATATYPE  H5T_STD_I32LE
            DATASPACE  SCALAR
            DATA {
            (0): 101
            }
         }
...
         DATASET "Signal" {
            DATATYPE  H5T_STD_I16LE
            DATASPACE  SIMPLE { ( 436555 ) / ( 436555 ) }
            DATA {

[******The raw signal should be here but instead there is a message saying h5dump error: unable to print data******]
            }
         }

I have tried on a few machines with no luck, including the C API directly. Can you confirm that your original files have this data? Thank you!

**Comment by hyeshik** [comment]
Dear @nodrogluap,

Thank you for reaching out to me!
Some of our data were compressed with [Oxford Nanopore's vbz codec](https://github.com/nanoporetech/vbz_compression). The raw signal data may not be recognized correctly before installing the plug-in.

Thank you!

**Comment by nodrogluap** [comment]
Thanks for the tip.  I compiled the vbz plugin, then h5dump and my C code both work fine by prepending the command with HDF5_PLUGIN_PATH=path/to/git/compiled/vbz_compression/build/bin
