### ISSUE TITLE
What kind of reference sequence does tombo resquiggle use?

### ISSUE THREAD

**Issue by weir12** [hyeshik/sars-cov-2-transcriptome#2]
Hi:
Thank you for the raw data provided.
As we know,For processing RNA data  requires a **transcriptome** due to the lack of spliced mapping support within the `Tombo`.On the other hand,numerous recombination events of covid19 was found in your research project...So,I think using the genome as reference file in  **re-squiggle** processing of `tombo` is NOT a wise choice.However,The virus does not appear to contain introns.Perhaps not bad mapping results could also be achieved using the genome.
I am confused about this problem.could you provide reference sequence which used in `tombo re-squiggle`?
Welcome to correct my viewpoint if there are any errors in my concept.
Many thanks.

**Comment by hyeshik** [comment]
Hi @weir12,
We have used the viral genome sequence for resquiggling.
As you already guessed, we could get high-quality resquiggling results even without using transcriptome as a reference. Aligning RNA sequence to viral genome is a lot less ambiguous than aligning to a eukaryotic transcriptome. We could use significantly sensitized options for alignments. As you pointed out, it would be good if we could incorporate the recombinations in the sgRNA production. However, it becomes too complex, then. As tombo only picks up well-aligned sequences in the analysis by default, only the molecules without discontinuous mappings were reflected in the modification detection. Thus, our RNA modification analyses cover only canonical sgRNAs.

Thank you!
Hyeshik

**Comment by weir12** [comment]
Thank you for your kind reply!
weir
